### ISSUE TITLE
MarchMadness.py error

### ISSUE THREAD

**Issue by nickmalbsn** [adeshpande3/March-Madness-ML#27]
Traceback (most recent call last):
  File "MarchMadness.py", line 22, in <module>
    from keras.utils import np_utils
  File "C:\Users\Nick Jwaida\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\keras\__init__.py", line 21, in <module>
    from keras import models
  File "C:\Users\Nick Jwaida\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\keras\models\__init__.py", line 18, in <module>
    from keras.engine.functional import Functional
  File "C:\Users\Nick Jwaida\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\keras\engine\functional.py", line 24, in <module>
    import tensorflow.compat.v2 as tf
  File "C:\Users\Nick Jwaida\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
ModuleNotFoundError: No module named 'tensorflow.python'

**Comment by adeshpande3** [comment]
Hmm this one is interesting. Seems like the root issue is that it can't find a particular tensorflow variable, but not sure why the keras installation didn't handle it. 

Looked at where that lib is being used, and it doesn't seem like it actually is, so honestly would recommend just removing that import (although might potentially cause a downstream error)

<img width="713" alt="image" src="https://user-images.githubusercontent.com/13543909/225202413-9e4d6deb-1da3-41ab-99bf-d012e92d6352.png">
